# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/service/auth/v3/external_auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/service/auth/v3/external_auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
from fulcrum_grpc_api.envoy.config.core.v3 import base_pb2 as fulcrum__grpc__api_dot_envoy_dot_config_dot_core_dot_v3_dot_base__pb2
from fulcrum_grpc_api.envoy.service.auth.v3 import attribute_context_pb2 as fulcrum__grpc__api_dot_envoy_dot_service_dot_auth_dot_v3_dot_attribute__context__pb2
from fulcrum_grpc_api.envoy.type.v3 import http_status_pb2 as fulcrum__grpc__api_dot_envoy_dot_type_dot_v3_dot_http__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:fulcrum_grpc_api/envoy/service/auth/v3/external_auth.proto\x12\x15\x65nvoy.service.auth.v3\x1a\x17google/rpc/status.proto\x1a\x30\x66ulcrum_grpc_api/envoy/config/core/v3/base.proto\x1a>fulcrum_grpc_api/envoy/service/auth/v3/attribute_context.proto\x1a\x30\x66ulcrum_grpc_api/envoy/type/v3/http_status.proto\"K\n\x0c\x43heckRequest\x12;\n\nattributes\x18\x01 \x01(\x0b\x32\'.envoy.service.auth.v3.AttributeContext\"\x87\x01\n\x12\x44\x65niedHttpResponse\x12)\n\x06status\x18\x01 \x01(\x0b\x32\x19.envoy.type.v3.HttpStatus\x12\x38\n\x07headers\x18\x02 \x03(\x0b\x32\'.envoy.config.core.v3.HeaderValueOption\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"J\n\x0eOkHttpResponse\x12\x38\n\x07headers\x18\x02 \x03(\x0b\x32\'.envoy.config.core.v3.HeaderValueOption\"\xc8\x01\n\rCheckResponse\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.google.rpc.Status\x12\x44\n\x0f\x64\x65nied_response\x18\x02 \x01(\x0b\x32).envoy.service.auth.v3.DeniedHttpResponseH\x00\x12<\n\x0bok_response\x18\x03 \x01(\x0b\x32%.envoy.service.auth.v3.OkHttpResponseH\x00\x42\x0f\n\rhttp_response2c\n\rAuthorization\x12R\n\x05\x43heck\x12#.envoy.service.auth.v3.CheckRequest\x1a$.envoy.service.auth.v3.CheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.service.auth.v3.external_auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKREQUEST']._serialized_start=274
  _globals['_CHECKREQUEST']._serialized_end=349
  _globals['_DENIEDHTTPRESPONSE']._serialized_start=352
  _globals['_DENIEDHTTPRESPONSE']._serialized_end=487
  _globals['_OKHTTPRESPONSE']._serialized_start=489
  _globals['_OKHTTPRESPONSE']._serialized_end=563
  _globals['_CHECKRESPONSE']._serialized_start=566
  _globals['_CHECKRESPONSE']._serialized_end=766
  _globals['_AUTHORIZATION']._serialized_start=768
  _globals['_AUTHORIZATION']._serialized_end=867
# @@protoc_insertion_point(module_scope)
