syntax = "proto3";

package envoy.service.auth.v3;

import "google/rpc/status.proto";

service Authorization {
  rpc Check(CheckRequest) returns (CheckResponse);
}

message HeaderValue {
  string key = 1;
  string value = 2;
}

message HeaderValueOption {
  HeaderValue header = 1;
}

message HttpStatus {
  enum Code {
    Empty = 0;
    OK = 200;
    Unauthorized = 401;
    Forbidden = 403;
  }

  Code code = 1;
}

message AttributeContext {
  message Peer {
    string principal = 1;
  }

  message Request {
    message HttpRequest {
      string id = 1;
      string method = 2;
      map<string, string> headers = 3;
      string path = 4;
      string host = 5;
      string scheme = 6;
      string query = 7;
      string fragment = 8;
      int64 size = 9;
      string protocol = 10;
      string body = 11;
      bytes raw_body = 12;
    }

    HttpRequest http = 2;
  }

  Peer source = 1;
  Peer destination = 2;
  Request request = 4;
}

message CheckRequest {
  AttributeContext attributes = 1;
}

message DeniedHttpResponse {
  HttpStatus status = 1;
  repeated HeaderValueOption headers = 2;
  string body = 3;
}

message OkHttpResponse {
  repeated HeaderValueOption headers = 2;
}

message CheckResponse {
  google.rpc.Status status = 1;

  oneof http_response {
    DeniedHttpResponse denied_response = 2;
    OkHttpResponse ok_response = 3;
  }
}
