# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/extensions/filters/http/ratelimit/v3/rate_limit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/extensions/filters/http/ratelimit/v3/rate_limit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from fulcrum_grpc_api.envoy.config.ratelimit.v3 import rls_pb2 as fulcrum__grpc__api_dot_envoy_dot_config_dot_ratelimit_dot_v3_dot_rls__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLfulcrum_grpc_api/envoy/extensions/filters/http/ratelimit/v3/rate_limit.proto\x12*envoy.extensions.filters.http.ratelimit.v3\x1a\x1egoogle/protobuf/duration.proto\x1a\x34\x66ulcrum_grpc_api/envoy/config/ratelimit/v3/rls.proto\"\xb1\x01\n\tRateLimit\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12*\n\x07timeout\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x19\n\x11\x66\x61ilure_mode_deny\x18\x05 \x01(\x08\x12M\n\x12rate_limit_service\x18\x07 \x01(\x0b\x32\x31.envoy.config.ratelimit.v3.RateLimitServiceConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.extensions.filters.http.ratelimit.v3.rate_limit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATELIMIT']._serialized_start=211
  _globals['_RATELIMIT']._serialized_end=388
# @@protoc_insertion_point(module_scope)
