# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/config/route/v3/route.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/config/route/v3/route.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2fulcrum_grpc_api/envoy/config/route/v3/route.proto\x12\x15\x65nvoy.config.route.v3\x1a\x1egoogle/protobuf/duration.proto\"]\n\x12RouteConfiguration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x39\n\rvirtual_hosts\x18\x02 \x03(\x0b\x32\".envoy.config.route.v3.VirtualHost\"Z\n\x0bVirtualHost\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x64omains\x18\x02 \x03(\t\x12,\n\x06routes\x18\x03 \x03(\x0b\x32\x1c.envoy.config.route.v3.Route\"l\n\x05Route\x12\x30\n\x05match\x18\x01 \x01(\x0b\x32!.envoy.config.route.v3.RouteMatch\x12\x31\n\x05route\x18\x02 \x01(\x0b\x32\".envoy.config.route.v3.RouteAction\"\x1c\n\nRouteMatch\x12\x0e\n\x06prefix\x18\x01 \x01(\t\"\x81\x01\n\x0bRouteAction\x12\x0f\n\x07\x63luster\x18\x01 \x01(\t\x12*\n\x07timeout\x18\x08 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x35\n\x0brate_limits\x18\r \x03(\x0b\x32 .envoy.config.route.v3.RateLimit\"\x86\x02\n\tRateLimit\x12\x38\n\x07\x61\x63tions\x18\x03 \x03(\x0b\x32\'.envoy.config.route.v3.RateLimit.Action\x1a\xbe\x01\n\x06\x41\x63tion\x12I\n\x0bgeneric_key\x18\x05 \x01(\x0b\x32\x32.envoy.config.route.v3.RateLimit.Action.GenericKeyH\x00\x1aU\n\nGenericKey\x12\x18\n\x10\x64\x65scriptor_value\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65scriptor_key\x18\x02 \x01(\t\x12\x15\n\rdefault_value\x18\x03 \x01(\tB\x12\n\x10\x61\x63tion_specifierb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.config.route.v3.route_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTECONFIGURATION']._serialized_start=109
  _globals['_ROUTECONFIGURATION']._serialized_end=202
  _globals['_VIRTUALHOST']._serialized_start=204
  _globals['_VIRTUALHOST']._serialized_end=294
  _globals['_ROUTE']._serialized_start=296
  _globals['_ROUTE']._serialized_end=404
  _globals['_ROUTEMATCH']._serialized_start=406
  _globals['_ROUTEMATCH']._serialized_end=434
  _globals['_ROUTEACTION']._serialized_start=437
  _globals['_ROUTEACTION']._serialized_end=566
  _globals['_RATELIMIT']._serialized_start=569
  _globals['_RATELIMIT']._serialized_end=831
  _globals['_RATELIMIT_ACTION']._serialized_start=641
  _globals['_RATELIMIT_ACTION']._serialized_end=831
  _globals['_RATELIMIT_ACTION_GENERICKEY']._serialized_start=726
  _globals['_RATELIMIT_ACTION_GENERICKEY']._serialized_end=811
# @@protoc_insertion_point(module_scope)
