# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fulcrum_grpc_api.envoy.config.core.v3 import grpc_service_pb2 as fulcrum__grpc__api_dot_envoy_dot_config_dot_core_dot_v3_dot_grpc__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKfulcrum_grpc_api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto\x12*envoy.extensions.filters.http.ext_authz.v3\x1a\x38\x66ulcrum_grpc_api/envoy/config/core/v3/grpc_service.proto\"m\n\x08\x45xtAuthz\x12\x39\n\x0cgrpc_service\x18\x01 \x01(\x0b\x32!.envoy.config.core.v3.GrpcServiceH\x00\x12\x1a\n\x12\x66\x61ilure_mode_allow\x18\x02 \x01(\x08\x42\n\n\x08servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.extensions.filters.http.ext_authz.v3.ext_authz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTAUTHZ']._serialized_start=181
  _globals['_EXTAUTHZ']._serialized_end=290
# @@protoc_insertion_point(module_scope)
