# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/config/listener/v3/listener.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/config/listener/v3/listener.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8fulcrum_grpc_api/envoy/config/listener/v3/listener.proto\x12\x18\x65nvoy.config.listener.v3\x1a\x19google/protobuf/any.proto\"\x8a\x01\n\x08Listener\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32!.envoy.config.listener.v3.Address\x12<\n\rfilter_chains\x18\x03 \x03(\x0b\x32%.envoy.config.listener.v3.FilterChain\"J\n\x07\x41\x64\x64ress\x12?\n\x0esocket_address\x18\x01 \x01(\x0b\x32\'.envoy.config.listener.v3.SocketAddress\"4\n\rSocketAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x12\n\nport_value\x18\x03 \x01(\r\"@\n\x0b\x46ilterChain\x12\x31\n\x07\x66ilters\x18\x03 \x03(\x0b\x32 .envoy.config.listener.v3.Filter\"B\n\x06\x46ilter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x0ctyped_config\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.config.listener.v3.listener_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTENER']._serialized_start=114
  _globals['_LISTENER']._serialized_end=252
  _globals['_ADDRESS']._serialized_start=254
  _globals['_ADDRESS']._serialized_end=328
  _globals['_SOCKETADDRESS']._serialized_start=330
  _globals['_SOCKETADDRESS']._serialized_end=382
  _globals['_FILTERCHAIN']._serialized_start=384
  _globals['_FILTERCHAIN']._serialized_end=448
  _globals['_FILTER']._serialized_start=450
  _globals['_FILTER']._serialized_end=516
# @@protoc_insertion_point(module_scope)
