# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/service/discovery/v3/ads.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/service/discovery/v3/ads.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5fulcrum_grpc_api/envoy/service/discovery/v3/ads.proto\x12\x1a\x65nvoy.service.discovery.v3\x1a\x19google/protobuf/any.proto\x1a\x17google/rpc/status.proto\"#\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63luster\x18\x02 \x01(\t\"\"\n\x0c\x43ontrolPlane\x12\x12\n\nidentifier\x18\x01 \x01(\t\"\xc4\x01\n\x10\x44iscoveryRequest\x12\x14\n\x0cversion_info\x18\x01 \x01(\t\x12.\n\x04node\x18\x02 \x01(\x0b\x32 .envoy.service.discovery.v3.Node\x12\x16\n\x0eresource_names\x18\x03 \x03(\t\x12\x10\n\x08type_url\x18\x04 \x01(\t\x12\x16\n\x0eresponse_nonce\x18\x05 \x01(\t\x12(\n\x0c\x65rror_detail\x18\x06 \x01(\x0b\x32\x12.google.rpc.Status\"\xc4\x01\n\x11\x44iscoveryResponse\x12\x14\n\x0cversion_info\x18\x01 \x01(\t\x12\'\n\tresources\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x0e\n\x06\x63\x61nary\x18\x03 \x01(\x08\x12\x10\n\x08type_url\x18\x04 \x01(\t\x12\r\n\x05nonce\x18\x05 \x01(\t\x12?\n\rcontrol_plane\x18\x06 \x01(\x0b\x32(.envoy.service.discovery.v3.ControlPlane2\x9a\x01\n\x1a\x41ggregatedDiscoveryService\x12|\n\x19StreamAggregatedResources\x12,.envoy.service.discovery.v3.DiscoveryRequest\x1a-.envoy.service.discovery.v3.DiscoveryResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.service.discovery.v3.ads_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODE']._serialized_start=137
  _globals['_NODE']._serialized_end=172
  _globals['_CONTROLPLANE']._serialized_start=174
  _globals['_CONTROLPLANE']._serialized_end=208
  _globals['_DISCOVERYREQUEST']._serialized_start=211
  _globals['_DISCOVERYREQUEST']._serialized_end=407
  _globals['_DISCOVERYRESPONSE']._serialized_start=410
  _globals['_DISCOVERYRESPONSE']._serialized_end=606
  _globals['_AGGREGATEDDISCOVERYSERVICE']._serialized_start=609
  _globals['_AGGREGATEDDISCOVERYSERVICE']._serialized_end=763
# @@protoc_insertion_point(module_scope)
