syntax = "proto3";

package envoy.config.cluster.v3;

message Cluster {
  enum DiscoveryType {
    STATIC = 0;
    STRICT_DNS = 1;
    LOGICAL_DNS = 2;
    EDS = 3;
    ORIGINAL_DST = 4;
  }

  enum LbPolicy {
    ROUND_ROBIN = 0;
  }

  string name = 1;
  DiscoveryType type = 2;
  LbPolicy lb_policy = 6;
  ClusterLoadAssignment load_assignment = 33;
}

message ClusterLoadAssignment {
  string cluster_name = 1;
  repeated LocalityLbEndpoints endpoints = 2;
}

message LocalityLbEndpoints {
  repeated LbEndpoint lb_endpoints = 2;
}

message LbEndpoint {
  Endpoint endpoint = 1;
}

message Endpoint {
  Address address = 1;
}

message Address {
  SocketAddress socket_address = 1;
}

message SocketAddress {
  string address = 2;
  uint32 port_value = 3;
}
