# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/config/cluster/v3/cluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/config/cluster/v3/cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6fulcrum_grpc_api/envoy/config/cluster/v3/cluster.proto\x12\x17\x65nvoy.config.cluster.v3\"\xd2\x02\n\x07\x43luster\x12\x0c\n\x04name\x18\x01 \x01(\t\x12<\n\x04type\x18\x02 \x01(\x0e\x32..envoy.config.cluster.v3.Cluster.DiscoveryType\x12<\n\tlb_policy\x18\x06 \x01(\x0e\x32).envoy.config.cluster.v3.Cluster.LbPolicy\x12G\n\x0fload_assignment\x18! \x01(\x0b\x32..envoy.config.cluster.v3.ClusterLoadAssignment\"W\n\rDiscoveryType\x12\n\n\x06STATIC\x10\x00\x12\x0e\n\nSTRICT_DNS\x10\x01\x12\x0f\n\x0bLOGICAL_DNS\x10\x02\x12\x07\n\x03\x45\x44S\x10\x03\x12\x10\n\x0cORIGINAL_DST\x10\x04\"\x1b\n\x08LbPolicy\x12\x0f\n\x0bROUND_ROBIN\x10\x00\"n\n\x15\x43lusterLoadAssignment\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12?\n\tendpoints\x18\x02 \x03(\x0b\x32,.envoy.config.cluster.v3.LocalityLbEndpoints\"P\n\x13LocalityLbEndpoints\x12\x39\n\x0clb_endpoints\x18\x02 \x03(\x0b\x32#.envoy.config.cluster.v3.LbEndpoint\"A\n\nLbEndpoint\x12\x33\n\x08\x65ndpoint\x18\x01 \x01(\x0b\x32!.envoy.config.cluster.v3.Endpoint\"=\n\x08\x45ndpoint\x12\x31\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32 .envoy.config.cluster.v3.Address\"I\n\x07\x41\x64\x64ress\x12>\n\x0esocket_address\x18\x01 \x01(\x0b\x32&.envoy.config.cluster.v3.SocketAddress\"4\n\rSocketAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x12\n\nport_value\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.config.cluster.v3.cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLUSTER']._serialized_start=84
  _globals['_CLUSTER']._serialized_end=422
  _globals['_CLUSTER_DISCOVERYTYPE']._serialized_start=306
  _globals['_CLUSTER_DISCOVERYTYPE']._serialized_end=393
  _globals['_CLUSTER_LBPOLICY']._serialized_start=395
  _globals['_CLUSTER_LBPOLICY']._serialized_end=422
  _globals['_CLUSTERLOADASSIGNMENT']._serialized_start=424
  _globals['_CLUSTERLOADASSIGNMENT']._serialized_end=534
  _globals['_LOCALITYLBENDPOINTS']._serialized_start=536
  _globals['_LOCALITYLBENDPOINTS']._serialized_end=616
  _globals['_LBENDPOINT']._serialized_start=618
  _globals['_LBENDPOINT']._serialized_end=683
  _globals['_ENDPOINT']._serialized_start=685
  _globals['_ENDPOINT']._serialized_end=746
  _globals['_ADDRESS']._serialized_start=748
  _globals['_ADDRESS']._serialized_end=821
  _globals['_SOCKETADDRESS']._serialized_start=823
  _globals['_SOCKETADDRESS']._serialized_end=875
# @@protoc_insertion_point(module_scope)
