# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/config/endpoint/v3/endpoint.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/config/endpoint/v3/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8fulcrum_grpc_api/envoy/config/endpoint/v3/endpoint.proto\x12\x18\x65nvoy.config.endpoint.v3\"o\n\x15\x43lusterLoadAssignment\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12@\n\tendpoints\x18\x02 \x03(\x0b\x32-.envoy.config.endpoint.v3.LocalityLbEndpoints\"Q\n\x13LocalityLbEndpoints\x12:\n\x0clb_endpoints\x18\x02 \x03(\x0b\x32$.envoy.config.endpoint.v3.LbEndpoint\"B\n\nLbEndpoint\x12\x34\n\x08\x65ndpoint\x18\x01 \x01(\x0b\x32\".envoy.config.endpoint.v3.Endpoint\">\n\x08\x45ndpoint\x12\x32\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32!.envoy.config.endpoint.v3.Address\"J\n\x07\x41\x64\x64ress\x12?\n\x0esocket_address\x18\x01 \x01(\x0b\x32\'.envoy.config.endpoint.v3.SocketAddress\"4\n\rSocketAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x12\n\nport_value\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.config.endpoint.v3.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLUSTERLOADASSIGNMENT']._serialized_start=86
  _globals['_CLUSTERLOADASSIGNMENT']._serialized_end=197
  _globals['_LOCALITYLBENDPOINTS']._serialized_start=199
  _globals['_LOCALITYLBENDPOINTS']._serialized_end=280
  _globals['_LBENDPOINT']._serialized_start=282
  _globals['_LBENDPOINT']._serialized_end=348
  _globals['_ENDPOINT']._serialized_start=350
  _globals['_ENDPOINT']._serialized_end=412
  _globals['_ADDRESS']._serialized_start=414
  _globals['_ADDRESS']._serialized_end=488
  _globals['_SOCKETADDRESS']._serialized_start=490
  _globals['_SOCKETADDRESS']._serialized_end=542
# @@protoc_insertion_point(module_scope)
