syntax = "proto3";

package envoy.extensions.common.ratelimit.v3;

import "google/protobuf/wrappers.proto";
import "fulcrum_grpc_api/envoy/type/v3/ratelimit_unit.proto";

// A hierarchical list of key/value entries used to select a rate limit bucket.
message RateLimitDescriptor {
  message Entry {
    string key = 1;
    string value = 2;
  }

  message RateLimitOverride {
    uint32 requests_per_unit = 1;
    envoy.type.v3.RateLimitUnit unit = 2;
  }

  repeated Entry entries = 1;
  RateLimitOverride limit = 2;
  google.protobuf.UInt64Value hits_addend = 3;
  bool is_negative_hits = 4;
}
