# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fulcrum_grpc_api/envoy/extensions/common/ratelimit/v3/ratelimit.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from fulcrum_grpc_api.envoy.type.v3 import ratelimit_unit_pb2 as fulcrum__grpc__api_dot_envoy_dot_type_dot_v3_dot_ratelimit__unit__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEfulcrum_grpc_api/envoy/extensions/common/ratelimit/v3/ratelimit.proto\x12$envoy.extensions.common.ratelimit.v3\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x33\x66ulcrum_grpc_api/envoy/type/v3/ratelimit_unit.proto\"\x91\x03\n\x13RateLimitDescriptor\x12P\n\x07\x65ntries\x18\x01 \x03(\x0b\x32?.envoy.extensions.common.ratelimit.v3.RateLimitDescriptor.Entry\x12Z\n\x05limit\x18\x02 \x01(\x0b\x32K.envoy.extensions.common.ratelimit.v3.RateLimitDescriptor.RateLimitOverride\x12\x31\n\x0bhits_addend\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12\x18\n\x10is_negative_hits\x18\x04 \x01(\x08\x1a#\n\x05\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x1aZ\n\x11RateLimitOverride\x12\x19\n\x11requests_per_unit\x18\x01 \x01(\r\x12*\n\x04unit\x18\x02 \x01(\x0e\x32\x1c.envoy.type.v3.RateLimitUnitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.extensions.common.ratelimit.v3.ratelimit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATELIMITDESCRIPTOR']._serialized_start=197
  _globals['_RATELIMITDESCRIPTOR']._serialized_end=598
  _globals['_RATELIMITDESCRIPTOR_ENTRY']._serialized_start=471
  _globals['_RATELIMITDESCRIPTOR_ENTRY']._serialized_end=506
  _globals['_RATELIMITDESCRIPTOR_RATELIMITOVERRIDE']._serialized_start=508
  _globals['_RATELIMITDESCRIPTOR_RATELIMITOVERRIDE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
