# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/config/ratelimit/v3/rls.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/config/ratelimit/v3/rls.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fulcrum_grpc_api.envoy.config.core.v3 import grpc_service_pb2 as fulcrum__grpc__api_dot_envoy_dot_config_dot_core_dot_v3_dot_grpc__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4fulcrum_grpc_api/envoy/config/ratelimit/v3/rls.proto\x12\x19\x65nvoy.config.ratelimit.v3\x1a\x38\x66ulcrum_grpc_api/envoy/config/core/v3/grpc_service.proto\"Q\n\x16RateLimitServiceConfig\x12\x37\n\x0cgrpc_service\x18\x02 \x01(\x0b\x32!.envoy.config.core.v3.GrpcServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.config.ratelimit.v3.rls_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATELIMITSERVICECONFIG']._serialized_start=141
  _globals['_RATELIMITSERVICECONFIG']._serialized_end=222
# @@protoc_insertion_point(module_scope)
