[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "auth-sidecar"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fulcrum-grpc-api",
    "googleapis-common-protos>=1.75",
    "grpcio>=1.64.1",
]

[tool.hatch.build.targets.wheel]
packages = ["auth_sidecar"]
