syntax = "proto3";

package envoy.service.ratelimit.v3;

import "google/protobuf/duration.proto";
import "google/protobuf/struct.proto";
import "fulcrum_grpc_api/envoy/config/core/v3/base.proto";
import "fulcrum_grpc_api/envoy/extensions/common/ratelimit/v3/ratelimit.proto";

service RateLimitService {
  rpc ShouldRateLimit(RateLimitRequest) returns (RateLimitResponse);
}

message RateLimitRequest {
  string domain = 1;
  repeated envoy.extensions.common.ratelimit.v3.RateLimitDescriptor descriptors = 2;
  uint32 hits_addend = 3;
}

message RateLimitResponse {
  enum Code {
    UNKNOWN = 0;
    OK = 1;
    OVER_LIMIT = 2;
  }

  message RateLimit {
    enum Unit {
      UNKNOWN = 0;
      SECOND = 1;
      MINUTE = 2;
      HOUR = 3;
      DAY = 4;
      WEEK = 5;
      MONTH = 6;
      YEAR = 7;
    }

    string name = 1;
    uint32 requests_per_unit = 2;
    Unit unit = 3;
  }

  message DescriptorStatus {
    Code code = 1;
    RateLimit current_limit = 2;
    uint32 limit_remaining = 3;
    google.protobuf.Duration duration_until_reset = 4;
  }

  Code overall_code = 1;
  repeated DescriptorStatus statuses = 2;
  repeated envoy.config.core.v3.HeaderValue response_headers_to_add = 3;
  repeated envoy.config.core.v3.HeaderValue request_headers_to_add = 4;
  bytes raw_body = 5;
  google.protobuf.Struct dynamic_metadata = 6;
}
