# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fulcrum_grpc_api.envoy.service.ratelimit.v3 import rls_pb2 as fulcrum__grpc__api_dot_envoy_dot_service_dot_ratelimit_dot_v3_dot_rls__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fulcrum_grpc_api/envoy/service/ratelimit/v3/rls_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RateLimitServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShouldRateLimit = channel.unary_unary(
                '/envoy.service.ratelimit.v3.RateLimitService/ShouldRateLimit',
                request_serializer=fulcrum__grpc__api_dot_envoy_dot_service_dot_ratelimit_dot_v3_dot_rls__pb2.RateLimitRequest.SerializeToString,
                response_deserializer=fulcrum__grpc__api_dot_envoy_dot_service_dot_ratelimit_dot_v3_dot_rls__pb2.RateLimitResponse.FromString,
                _registered_method=True)


class RateLimitServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ShouldRateLimit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateLimitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShouldRateLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.ShouldRateLimit,
                    request_deserializer=fulcrum__grpc__api_dot_envoy_dot_service_dot_ratelimit_dot_v3_dot_rls__pb2.RateLimitRequest.FromString,
                    response_serializer=fulcrum__grpc__api_dot_envoy_dot_service_dot_ratelimit_dot_v3_dot_rls__pb2.RateLimitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'envoy.service.ratelimit.v3.RateLimitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('envoy.service.ratelimit.v3.RateLimitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RateLimitService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShouldRateLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/envoy.service.ratelimit.v3.RateLimitService/ShouldRateLimit',
            fulcrum__grpc__api_dot_envoy_dot_service_dot_ratelimit_dot_v3_dot_rls__pb2.RateLimitRequest.SerializeToString,
            fulcrum__grpc__api_dot_envoy_dot_service_dot_ratelimit_dot_v3_dot_rls__pb2.RateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
