# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/config/core/v3/config_source.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/config/core/v3/config_source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9fulcrum_grpc_api/envoy/config/core/v3/config_source.proto\x12\x14\x65nvoy.config.core.v3\"\x18\n\x16\x41ggregatedConfigSource\"f\n\x0c\x43onfigSource\x12;\n\x03\x61\x64s\x18\x03 \x01(\x0b\x32,.envoy.config.core.v3.AggregatedConfigSourceH\x00\x42\x19\n\x17\x63onfig_source_specifierb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.config.core.v3.config_source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGGREGATEDCONFIGSOURCE']._serialized_start=83
  _globals['_AGGREGATEDCONFIGSOURCE']._serialized_end=107
  _globals['_CONFIGSOURCE']._serialized_start=109
  _globals['_CONFIGSOURCE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
