# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulcrum_grpc_api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fulcrum_grpc_api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from fulcrum_grpc_api.envoy.config.core.v3 import config_source_pb2 as fulcrum__grpc__api_dot_envoy_dot_config_dot_core_dot_v3_dot_config__source__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\njfulcrum_grpc_api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto\x12;envoy.extensions.filters.network.http_connection_manager.v3\x1a\x19google/protobuf/any.proto\x1a\x39\x66ulcrum_grpc_api/envoy/config/core/v3/config_source.proto\"\x84\x03\n\x15HttpConnectionManager\x12p\n\ncodec_type\x18\x01 \x01(\x0e\x32\\.envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager.CodecType\x12\x13\n\x0bstat_prefix\x18\x02 \x01(\t\x12M\n\x03rds\x18\x03 \x01(\x0b\x32@.envoy.extensions.filters.network.http_connection_manager.v3.Rds\x12]\n\x0chttp_filters\x18\x05 \x03(\x0b\x32G.envoy.extensions.filters.network.http_connection_manager.v3.HttpFilter\"6\n\tCodecType\x12\x08\n\x04\x41UTO\x10\x00\x12\t\n\x05HTTP1\x10\x01\x12\t\n\x05HTTP2\x10\x02\x12\t\n\x05HTTP3\x10\x03\"[\n\x03Rds\x12\x39\n\rconfig_source\x18\x01 \x01(\x0b\x32\".envoy.config.core.v3.ConfigSource\x12\x19\n\x11route_config_name\x18\x02 \x01(\t\"F\n\nHttpFilter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x0ctyped_config\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulcrum_grpc_api.envoy.extensions.filters.network.http_connection_manager.v3.http_connection_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HTTPCONNECTIONMANAGER']._serialized_start=258
  _globals['_HTTPCONNECTIONMANAGER']._serialized_end=646
  _globals['_HTTPCONNECTIONMANAGER_CODECTYPE']._serialized_start=592
  _globals['_HTTPCONNECTIONMANAGER_CODECTYPE']._serialized_end=646
  _globals['_RDS']._serialized_start=648
  _globals['_RDS']._serialized_end=739
  _globals['_HTTPFILTER']._serialized_start=741
  _globals['_HTTPFILTER']._serialized_end=811
# @@protoc_insertion_point(module_scope)
